/**
 * ses-otp-delivery-provider.test.ts — Unit tests for SesOtpDeliveryProvider.
 *
 * Specification (SPARC Phase S):
 *
 * AC-001: SES accepts delivery — MessageId returned; otp.delivery.sent logged at INFO
 *         with { emailDomain, messageId, correlationId }. Subject = 'Your CELLO verification code'.
 *         (Full integration test guarded by SES_INTEGRATION_TEST=true — AC-008.)
 *
 * AC-002: 6th sendOtp() within 1 hour throws RateLimitError before any SES call.
 *         Rate limit is per email address, per provider instance.
 *
 * AC-003: Rate limit counter resets after the 1-hour rolling window expires.
 *         After reset, the 1st send in the new window succeeds.
 *
 * AC-004: SES hard bounce → DeliveryError with sesErrorType='Bounce';
 *         otp.delivery.failed logged at ERROR with { emailDomain, sesErrorType, correlationId }.
 *         Second sendOtp() with the same bounced address returns immediate DeliveryError
 *         without calling SES.
 *
 * AC-005: SES throttling → 1-second wait → retry once.
 *         If retry succeeds: otp.delivery.retried logged at INFO with { emailDomain,
 *           retryDelayMs: 1000, correlationId }.
 *         If retry also fails: DeliveryError thrown.
 *
 * AC-006: ConsoleOtpDeliveryProvider prints OTP to stdout; no network call made.
 *         (ConsoleOtpDeliveryProvider already exists — verified with a quick smoke test.)
 *
 * AC-007: 100 OTPs generated by generateOtp() are all exactly 6 digits (000000–999999).
 *         Leading zeros preserved.
 *
 * SI-001: generateOtp() uses crypto CSPRNG (randomBytes), not Math.random().
 *         Verified by observing uniform distribution over 1000 samples.
 *
 * SI-002: Full email address never appears in any log call — only emailDomain.
 *         Unit test scans all log.info/error calls for the full address string.
 *
 * SI-003: SES client injected via constructor — provider never constructs its own.
 *         Unit test asserts the exact client instance passed in is used.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import pg from "pg";
import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
import { SesOtpDeliveryProvider, DeliveryError, RateLimitError } from "../ses/ses-otp-delivery-provider.js";
import { generateOtp } from "../registration/otp.js";
import { ConsoleOtpDeliveryProvider, LocalPreAuthorizationClient } from "@cello-protocol/interfaces/stubs";
import type { Logger, LogContext, MessagingChannel, ChannelIdentity } from "@cello-protocol/interfaces";
import { RegistrationEngine } from "../registration/engine.js";
import { RegistrationRepository } from "../registration/repository.js";

// ─── Logger stub ─────────────────────────────────────────────────────────────

function makeLogger(): Logger & {
  infoCalls: Array<{ event: string; context: LogContext | undefined }>;
  errorCalls: Array<{ event: string; errorOrContext: Error | LogContext | undefined; context: LogContext | undefined }>;
} {
  const infoCalls: Array<{ event: string; context: LogContext | undefined }> = [];
  const errorCalls: Array<{ event: string; errorOrContext: Error | LogContext | undefined; context: LogContext | undefined }> = [];
  return {
    infoCalls,
    errorCalls,
    debug: vi.fn(),
    info: vi.fn((event: string, context?: LogContext) => { infoCalls.push({ event, context }); }),
    warn: vi.fn(),
    error: vi.fn((event: string, errorOrContext?: Error | LogContext, context?: LogContext) => {
      errorCalls.push({ event, errorOrContext, context });
    }),
  };
}

// ─── SES client mock helpers ──────────────────────────────────────────────────

function makeSendMock(result: unknown) {
  return vi.fn().mockResolvedValue(result);
}

function makeThrottleThenSuccessMock(messageId: string) {
  const throttleError = Object.assign(new Error("Throttling"), { name: "ThrottlingException" });
  return vi
    .fn()
    .mockRejectedValueOnce(throttleError)
    .mockResolvedValueOnce({ MessageId: messageId });
}

function makeThrottleThenThrottleMock() {
  const throttleError = Object.assign(new Error("Throttling"), { name: "ThrottlingException" });
  return vi
    .fn()
    .mockRejectedValueOnce(throttleError)
    .mockRejectedValueOnce(throttleError);
}

/**
 * Build a fake SESClient whose send() method is replaced with the provided mock.
 * SI-003 compliance: we inject this instance and verify it is used.
 */
function buildFakeClient(sendMock: ReturnType<typeof vi.fn>): SESClient {
  const client = new SESClient({ region: "us-east-1" });
  vi.spyOn(client, "send").mockImplementation(sendMock as Parameters<typeof vi.spyOn>[1]);
  return client;
}

// ─── AC-001: Successful delivery ─────────────────────────────────────────────

describe("SesOtpDeliveryProvider — AC-001: successful delivery", () => {
  it("calls SES SendEmailCommand with correct subject and from address; logs otp.delivery.sent", async () => {
    const messageId = "abc-message-id-001";
    const sendMock = makeSendMock({ MessageId: messageId });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    await provider.sendOtp("user@example.com", "123456");

    // SES was called exactly once
    expect(sendMock).toHaveBeenCalledTimes(1);

    // Verify the command shape
    const command = sendMock.mock.calls[0][0] as SendEmailCommand;
    expect(command).toBeInstanceOf(SendEmailCommand);
    const input = command.input;
    expect(input.Message?.Subject?.Data).toBe("Your CELLO verification code");
    expect(input.Destination?.ToAddresses).toContain("user@example.com");
    expect(input.Source).toBe("noreply@cello.example.com");
    expect(input.Message?.Body?.Text?.Data).toContain("123456");

    // otp.delivery.sent logged at INFO with required fields
    expect(logger.infoCalls).toHaveLength(1);
    const sentEvent = logger.infoCalls[0];
    expect(sentEvent.event).toBe("otp.delivery.sent");
    expect(sentEvent.context?.emailDomain).toBe("example.com");
    expect(sentEvent.context?.messageId).toBe(messageId);
    expect(typeof sentEvent.context?.correlationId).toBe("string");
    expect((sentEvent.context?.correlationId as string).length).toBeGreaterThan(0);
  });
});

// ─── AC-002: Rate limiting — 6th send throws RateLimitError ──────────────────

describe("SesOtpDeliveryProvider — AC-002: rate limiting", () => {
  it("throws RateLimitError on the 6th sendOtp() call within 1 hour, without calling SES", async () => {
    const sendMock = makeSendMock({ MessageId: "msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // First 5 sends succeed
    for (let i = 0; i < 5; i++) {
      await provider.sendOtp("ratelimit@example.com", "111111");
    }

    expect(sendMock).toHaveBeenCalledTimes(5);

    // 6th send throws RateLimitError
    await expect(provider.sendOtp("ratelimit@example.com", "111111")).rejects.toBeInstanceOf(RateLimitError);

    // SES was NOT called for the 6th attempt
    expect(sendMock).toHaveBeenCalledTimes(5);
  });

  it("rate limit is per email address — different addresses do not share limits", async () => {
    const sendMock = makeSendMock({ MessageId: "msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // Use up the limit for address A
    for (let i = 0; i < 5; i++) {
      await provider.sendOtp("a@example.com", "111111");
    }

    // Address B should still succeed
    await expect(provider.sendOtp("b@example.com", "111111")).resolves.toBeUndefined();
    expect(sendMock).toHaveBeenCalledTimes(6);
  });

  it("RateLimitError message includes the email domain", async () => {
    const sendMock = makeSendMock({ MessageId: "msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    for (let i = 0; i < 5; i++) {
      await provider.sendOtp("user@domain.org", "999999");
    }

    const error = await provider.sendOtp("user@domain.org", "999999").catch((e: unknown) => e);
    expect(error).toBeInstanceOf(RateLimitError);
    expect((error as RateLimitError).name).toBe("RateLimitError");
    expect((error as RateLimitError).message).toContain("domain.org");
  });
});

// ─── AC-003: Rate limit window reset ─────────────────────────────────────────

describe("SesOtpDeliveryProvider — AC-003: rate limit window reset", () => {
  beforeEach(() => { vi.useFakeTimers(); });
  afterEach(() => { vi.useRealTimers(); });

  it("resets the counter after 1 hour and allows sends again", async () => {
    const sendMock = makeSendMock({ MessageId: "msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // Use up the limit
    for (let i = 0; i < 5; i++) {
      await provider.sendOtp("window@example.com", "111111");
    }

    // 6th within window → rate limited
    await expect(provider.sendOtp("window@example.com", "111111")).rejects.toBeInstanceOf(RateLimitError);

    // Advance time by 1 hour + 1 ms → window expires
    vi.advanceTimersByTime(60 * 60 * 1000 + 1);

    // First send after window reset should succeed
    await expect(provider.sendOtp("window@example.com", "111111")).resolves.toBeUndefined();
    await vi.runAllTimersAsync();
    expect(sendMock).toHaveBeenCalledTimes(6);
  });
});

// ─── AC-004: Hard bounce handling ────────────────────────────────────────────

describe("SesOtpDeliveryProvider — AC-004: hard bounce", () => {
  it("throws DeliveryError with sesErrorType='Bounce' on hard bounce; logs otp.delivery.failed", async () => {
    // SES MessageRejected maps to a hard bounce
    const bounceError = Object.assign(new Error("Email address blacklisted"), {
      name: "MessageRejected",
    });
    const sendMock = vi.fn().mockRejectedValue(bounceError);
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    const error = await provider.sendOtp("bounce@example.com", "444444").catch((e: unknown) => e);

    expect(error).toBeInstanceOf(DeliveryError);
    expect((error as DeliveryError).name).toBe("DeliveryError");
    expect((error as DeliveryError).sesErrorType).toBe("Bounce");

    // otp.delivery.failed logged at ERROR with correct fields
    expect(logger.errorCalls).toHaveLength(1);
    const failEvent = logger.errorCalls[0];
    expect(failEvent.event).toBe("otp.delivery.failed");
    // errorOrContext may be an Error object; context may carry the fields
    // depending on Logger.error(event, error, context) call form
    const ctx = failEvent.errorOrContext instanceof Error ? failEvent.context : failEvent.errorOrContext;
    expect(ctx?.emailDomain).toBe("example.com");
    expect(ctx?.sesErrorType).toBe("Bounce");
    expect(typeof ctx?.correlationId).toBe("string");
  });

  it("does not call SES on a second sendOtp() with the same bounced address", async () => {
    const bounceError = Object.assign(new Error("blacklisted"), { name: "MessageRejected" });
    const sendMock = vi.fn().mockRejectedValue(bounceError);
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // First call → bounce
    await provider.sendOtp("bounce@example.com", "555555").catch(() => undefined);
    expect(sendMock).toHaveBeenCalledTimes(1);

    // Second call with same address → immediate error, no SES call
    const error = await provider.sendOtp("bounce@example.com", "666666").catch((e: unknown) => e);
    expect(error).toBeInstanceOf(DeliveryError);
    expect((error as DeliveryError).sesErrorType).toBe("Bounce");
    // Still only 1 SES call total
    expect(sendMock).toHaveBeenCalledTimes(1);
  });

  it("a new provider instance starts with an empty bounced set", async () => {
    const bounceError = Object.assign(new Error("blacklisted"), { name: "MessageRejected" });
    const sendMock1 = vi.fn().mockRejectedValue(bounceError);
    const sesClient1 = buildFakeClient(sendMock1);
    const logger = makeLogger();

    const provider1 = new SesOtpDeliveryProvider({
      sesClient: sesClient1,
      fromAddress: "noreply@cello.example.com",
      logger,
    });
    await provider1.sendOtp("bounce@example.com", "111111").catch(() => undefined);

    // Provider 2 is fresh — address not in its bounced set
    const successMock = makeSendMock({ MessageId: "new-msg-id" });
    const sesClient2 = buildFakeClient(successMock);
    const provider2 = new SesOtpDeliveryProvider({
      sesClient: sesClient2,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    await expect(provider2.sendOtp("bounce@example.com", "222222")).resolves.toBeUndefined();
    expect(successMock).toHaveBeenCalledTimes(1);
  });
});

// ─── AC-005: Throttling retry ─────────────────────────────────────────────────

describe("SesOtpDeliveryProvider — AC-005: throttling retry", () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("retries after 1 second on ThrottlingException; logs otp.delivery.retried on success", async () => {
    const messageId = "retry-msg-id";
    const sendMock = makeThrottleThenSuccessMock(messageId);
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // Start the call — it will pause at the setTimeout
    const sendPromise = provider.sendOtp("throttle@example.com", "777777");

    // Advance fake timers past the 1-second retry delay
    await vi.runAllTimersAsync();

    await sendPromise;

    // SES was called twice (initial + retry)
    expect(sendMock).toHaveBeenCalledTimes(2);

    // otp.delivery.retried logged
    const retriedEvent = logger.infoCalls.find((c) => c.event === "otp.delivery.retried");
    expect(retriedEvent).toBeDefined();
    expect(retriedEvent?.context?.emailDomain).toBe("example.com");
    expect(retriedEvent?.context?.retryDelayMs).toBe(1000);
    expect(typeof retriedEvent?.context?.correlationId).toBe("string");

    // otp.delivery.sent also logged
    const sentEvent = logger.infoCalls.find((c) => c.event === "otp.delivery.sent");
    expect(sentEvent).toBeDefined();
    expect(sentEvent?.context?.messageId).toBe(messageId);
  });

  it("throws DeliveryError if the retry also fails", async () => {
    const sendMock = makeThrottleThenThrottleMock();
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // Attach the rejection handler synchronously before advancing timers,
    // so the rejection is handled immediately and does not become unhandled.
    const errorPromise = provider.sendOtp("throttle@example.com", "888888").catch((e: unknown) => e);

    // Advance fake timers past the 1-second retry delay
    await vi.runAllTimersAsync();

    const error = await errorPromise;
    expect(error).toBeInstanceOf(DeliveryError);

    // SES was called twice (initial + retry)
    expect(sendMock).toHaveBeenCalledTimes(2);

    // otp.delivery.failed logged
    const failEvent = logger.errorCalls.find((c) => c.event === "otp.delivery.failed");
    expect(failEvent).toBeDefined();
  });
});

// ─── AC-006: ConsoleOtpDeliveryProvider smoke test ───────────────────────────

describe("ConsoleOtpDeliveryProvider — AC-006: local stub", () => {
  it("writes OTP to stdout without throwing", async () => {
    const writeSpy = vi.spyOn(process.stdout, "write").mockImplementation(() => true);

    const provider = new ConsoleOtpDeliveryProvider();
    await expect(provider.sendOtp("dev@example.com", "123456")).resolves.toBeUndefined();

    expect(writeSpy).toHaveBeenCalledOnce();
    const written = writeSpy.mock.calls[0][0] as string;
    expect(written).toContain("123456");

    writeSpy.mockRestore();
  });

  it("does not make any network calls (no SES client needed)", () => {
    // Structural test: ConsoleOtpDeliveryProvider constructor takes no args.
    // If it required a SES client, the test would fail to compile.
    const provider = new ConsoleOtpDeliveryProvider();
    expect(provider).toBeDefined();
  });
});

// ─── AC-007: OTP format — 100 samples, all exactly 6 digits ──────────────────

describe("generateOtp — AC-007: 6-digit format invariant", () => {
  it("generates 100 OTPs that are all exactly 6 digits (000000–999999)", () => {
    const otps = Array.from({ length: 100 }, () => generateOtp());
    for (const otp of otps) {
      expect(otp).toMatch(/^\d{6}$/, `OTP '${otp}' is not exactly 6 digits`);
      const n = parseInt(otp, 10);
      expect(n).toBeGreaterThanOrEqual(0);
      expect(n).toBeLessThanOrEqual(999999);
    }
  });

  it("leading zeros are preserved (padStart(6, '0'))", () => {
    // We cannot force a specific value but we can verify the format contract
    // by checking that the string representation is always 6 chars wide.
    const otps = Array.from({ length: 100 }, () => generateOtp());
    for (const otp of otps) {
      expect(otp).toHaveLength(6);
    }
  });
});

// ─── SI-001: CSPRNG verification ─────────────────────────────────────────────

describe("generateOtp — SI-001: CSPRNG (not Math.random())", () => {
  it("produces a uniform-ish distribution over 1000 samples (Math.random() would cluster)", () => {
    // This test cannot distinguish crypto.randomInt from Math.random() via statistics alone
    // with only 1000 samples. However it documents the intent and catches a completely broken
    // implementation (e.g. always returning the same value).
    const seen = new Set<string>();
    for (let i = 0; i < 1000; i++) {
      seen.add(generateOtp());
    }
    // With a CSPRNG over 1,000,000 values, 1000 samples should yield close to 1000 unique values.
    // Even a very bad RNG would produce > 900 unique values in 1000 draws from 1M possibilities.
    expect(seen.size).toBeGreaterThan(900);
  });

  it("never calls Math.random() — confirms CSPRNG source (not pseudo-random)", () => {
    const spy = vi.spyOn(Math, "random");
    Array.from({ length: 100 }, () => generateOtp());
    expect(spy).not.toHaveBeenCalled();
    spy.mockRestore();
  });
});

// ─── SI-002: Email address never in logs ─────────────────────────────────────

describe("SesOtpDeliveryProvider — SI-002: domain-only logging", () => {
  it("never logs the full email address — only the domain portion", async () => {
    const fullEmail = "secret.user@private-domain.com";
    const sendMock = makeSendMock({ MessageId: "msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    await provider.sendOtp(fullEmail, "123456");

    // Collect all stringified log call arguments
    const allLoggedStrings = [
      ...logger.infoCalls.map((c) => JSON.stringify(c)),
      ...logger.errorCalls.map((c) => JSON.stringify(c)),
    ].join(" ");

    expect(allLoggedStrings).not.toContain(fullEmail);
    expect(allLoggedStrings).not.toContain("secret.user");
    expect(allLoggedStrings).toContain("private-domain.com");
  });

  it("logs [invalid-email-domain] when email has no @ sign (SI-002 defense-in-depth)", async () => {
    const noAtEmail = "notanemailaddress";
    const sendMock = makeSendMock({ MessageId: "msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    // sendOtp may succeed or fail — we only care that the raw string is never logged
    await provider.sendOtp(noAtEmail, "123456").catch(() => undefined);

    const allLoggedStrings = [
      ...logger.infoCalls.map((c) => JSON.stringify(c)),
      ...logger.errorCalls.map((c) => JSON.stringify(c)),
    ].join(" ");

    // Full no-@ address must not appear in logs
    expect(allLoggedStrings).not.toContain(noAtEmail);
    // The guard value must appear instead
    expect(allLoggedStrings).toContain("[invalid-email-domain]");
  });

  it("does not log full email on bounce either", async () => {
    const fullEmail = "bounce.secret@private-domain.net";
    const bounceError = Object.assign(new Error("blacklisted"), { name: "MessageRejected" });
    const sendMock = vi.fn().mockRejectedValue(bounceError);
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    await provider.sendOtp(fullEmail, "654321").catch(() => undefined);

    const allLoggedStrings = [
      ...logger.infoCalls.map((c) => JSON.stringify(c)),
      ...logger.errorCalls.map((c) => JSON.stringify(c)),
    ].join(" ");

    expect(allLoggedStrings).not.toContain(fullEmail);
    expect(allLoggedStrings).not.toContain("bounce.secret");
  });
});

// ─── SI-003: SES client injected, not constructed from env ───────────────────

describe("SesOtpDeliveryProvider — SI-003: injected SES client", () => {
  it("uses the exact SESClient instance passed to the constructor", async () => {
    const sendMock = makeSendMock({ MessageId: "si-003-msg-id" });
    const sesClient = buildFakeClient(sendMock);
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress: "noreply@cello.example.com",
      logger,
    });

    await provider.sendOtp("user@example.com", "123456");

    // The spy we placed on the injected client was invoked — proving the provider
    // used it rather than constructing a new one.
    expect(sendMock).toHaveBeenCalledTimes(1);
  });
});

// ─── AC-008: Integration gate ─────────────────────────────────────────────────
//
// Gated on BOTH:
//   process.env.CELLO_ENV === 'local'     — consistent with all other integration tests
//   process.env.SES_INTEGRATION_TEST === 'true'  — opt-in for SES-specific live tests
//
// In CI, neither env var is set, so this block is always skipped. That is expected.
//
// To run locally:
//   SES_INTEGRATION_TEST=true CELLO_ENV=local SES_SANDBOX_RECIPIENT=you@example.com \
//   pnpm --filter @cello-protocol/operations-agent run test -- --pool-options.threads.maxThreads=1
//
// Rate limit behaviour (AC-008-4) is exercised by the unit-level test at the bottom of
// this file (alongside AC-002 and AC-003) — it has no dependency on CELLO_ENV or
// SES_INTEGRATION_TEST and runs unconditionally in CI.

const isIntegrationEnabled =
  process.env["CELLO_ENV"] === "local" && process.env["SES_INTEGRATION_TEST"] === "true";

const DATABASE_URL_AC008 =
  process.env["DATABASE_URL"] ?? "postgresql://postgres:dev@localhost:5433/cello_dev";

const OPS_AGENT_URL_AC008 = DATABASE_URL_AC008.replace(
  /^(postgres(?:ql)?):\/\/[^:]+:[^@]+@/,
  "$1://cello_ops_agent:cello_ops_agent_dev@",
);

describe.skipIf(!isIntegrationEnabled)("AC-008 integration gate (SES_INTEGRATION_TEST=true required)", () => {
  let pool: pg.Pool;
  let repo: RegistrationRepository;

  beforeEach(async () => {
    pool = new pg.Pool({ connectionString: OPS_AGENT_URL_AC008 });
    repo = new RegistrationRepository(pool);

    // Flyway checksum gate — AC-008 requires zero checksum errors on all applied migrations.
    // This catches the FEDERATION-002 pattern where a previously-applied migration was
    // modified, causing Flyway to report a checksum mismatch on the next deployment.
    const flywayCheck = await pool.query(
      `SELECT COUNT(*) AS failed_count FROM flyway_schema_history WHERE success = false`,
    );
    expect(Number(flywayCheck.rows[0].failed_count)).toBe(0);
  });

  afterEach(async () => {
    await pool.end();
  });

  // ─── Part 1: SES acceptance — MessageId returned; otp.delivery.sent logged ────

  const sandboxRecipient = process.env["SES_SANDBOX_RECIPIENT"] ?? "";

  it.skipIf(!sandboxRecipient)("AC-008-1: SES accepts OTP delivery and otp.delivery.sent is logged with messageId", async () => {
    const fromAddress = process.env["SES_FROM_ADDRESS"] ?? "noreply@mail.mygentic.ai";

    // Use default AWS credential chain (env vars, IAM role, ~/.aws/credentials)
    const sesClient = new SESClient({ region: "us-east-1" });
    const logger = makeLogger();

    const provider = new SesOtpDeliveryProvider({
      sesClient,
      fromAddress,
      logger,
    });

    await provider.sendOtp(sandboxRecipient, "123456");

    // otp.delivery.sent must be logged with a non-empty messageId
    expect(logger.infoCalls).toHaveLength(1);
    const sentEvent = logger.infoCalls[0];
    expect(sentEvent.event).toBe("otp.delivery.sent");
    expect(typeof sentEvent.context?.messageId).toBe("string");
    expect((sentEvent.context?.messageId as string).length).toBeGreaterThan(0);
    expect(typeof sentEvent.context?.correlationId).toBe("string");
  });

  // ─── Part 2: State machine — correct OTP advances to PRE_AUTH_TOKEN_ISSUED ──

  it("AC-008-2: correct OTP drives state machine to PRE_AUTH_TOKEN_ISSUED", async () => {
    const userId = `ac008-correct-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
    const sent: Array<{ to: string; message: string }> = [];
    const captured: Array<{ emailAddress: string; otp: string }> = [];
    let messageHandler: ((from: string, message: string) => void | Promise<void>) | undefined;

    const channel: MessagingChannel = {
      async send(to: string, message: string): Promise<void> {
        sent.push({ to, message });
      },
      onMessage(h) {
        messageHandler = h;
      },
      async resolveIdentity(from: string): Promise<ChannelIdentity> {
        return { channel: "cli", channelUserId: from };
      },
    };

    const otpDelivery = {
      async sendOtp(emailAddress: string, otp: string): Promise<void> {
        captured.push({ emailAddress, otp });
      },
    };

    const logEvents: Array<{ method: string; event: string }> = [];
    const logger: Logger = {
      debug: (_e: string) => {},
      info: (event: string) => { logEvents.push({ method: "info", event }); },
      warn: (event: string) => { logEvents.push({ method: "warn", event }); },
      error: (event: string) => { logEvents.push({ method: "error", event }); },
    };

    async function inject(from: string, message: string): Promise<void> {
      if (messageHandler) await messageHandler(from, message);
    }

    const engine = new RegistrationEngine({
      pool,
      channel,
      otpDelivery,
      preAuth: new LocalPreAuthorizationClient(),
      logger,
      channelType: "cli",
      onError: (err) => { throw err; },
    });
    await engine.start();

    try {
      // Drive through: new user → phone contact → email address → correct OTP
      await inject(userId, "hello");
      await inject(userId, `CONTACT:${userId}:+447911555666`);
      await inject(userId, "ac008test@example.com");

      expect(captured.length).toBe(1);
      const otp = captured[0].otp;

      await inject(userId, otp);

      // Verify terminal state
      const rawResult = await pool.query(
        `SELECT state FROM registrations WHERE channel_user_id = $1 ORDER BY created_at DESC LIMIT 1`,
        [userId],
      );
      expect(rawResult.rows[0].state).toBe("PRE_AUTH_TOKEN_ISSUED");
    } finally {
      engine.stop();
      // Clean up: expire the record so it doesn't block future test runs
      try {
        const active = await repo.findActiveByChannelUser("cli", userId);
        if (active) {
          await repo.transition(active.id, "EXPIRED");
        }
      } catch { /* ignore cleanup errors */ }
    }
  });

  // ─── Part 3: State machine — expired OTP is rejected ─────────────────────

  it("AC-008-3: expired OTP is rejected; state does not advance beyond AWAITING_EMAIL_OTP", async () => {
    const userId = `ac008-expired-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
    const captured: Array<{ emailAddress: string; otp: string }> = [];
    const sent: Array<{ to: string; message: string }> = [];
    let messageHandler: ((from: string, message: string) => void | Promise<void>) | undefined;

    const channel: MessagingChannel = {
      async send(to: string, message: string): Promise<void> {
        sent.push({ to, message });
      },
      onMessage(h) { messageHandler = h; },
      async resolveIdentity(from: string): Promise<ChannelIdentity> {
        return { channel: "cli", channelUserId: from };
      },
    };

    const otpDelivery = {
      async sendOtp(emailAddress: string, otp: string): Promise<void> {
        captured.push({ emailAddress, otp });
      },
    };

    const logEvents: Array<{ method: string; event: string }> = [];
    const logger: Logger = {
      debug: (_e: string) => {},
      info: (event: string) => { logEvents.push({ method: "info", event }); },
      warn: (event: string) => { logEvents.push({ method: "warn", event }); },
      error: (event: string) => { logEvents.push({ method: "error", event }); },
    };

    async function inject(from: string, message: string): Promise<void> {
      if (messageHandler) await messageHandler(from, message);
    }

    const engine = new RegistrationEngine({
      pool,
      channel,
      otpDelivery,
      preAuth: new LocalPreAuthorizationClient(),
      logger,
      channelType: "cli",
      onError: (err) => { throw err; },
    });
    await engine.start();

    try {
      // Drive to AWAITING_EMAIL_OTP
      await inject(userId, "hello");
      await inject(userId, `CONTACT:${userId}:+447911777888`);
      await inject(userId, "expiredtest@example.com");

      expect(captured.length).toBe(1);
      const otp = captured[0].otp;

      // Manually expire the OTP via direct DB update
      await pool.query(
        `UPDATE registrations SET otp_expires_at = $1 WHERE channel_user_id = $2`,
        [new Date(Date.now() - 1000), userId],
      );

      // Submit the (now-expired) OTP
      await inject(userId, otp);

      // State must NOT have advanced to EMAIL_CONFIRMED or PRE_AUTH_TOKEN_ISSUED
      const rawResult = await pool.query(
        `SELECT state FROM registrations WHERE channel_user_id = $1 ORDER BY created_at DESC LIMIT 1`,
        [userId],
      );
      const stateAfter = rawResult.rows[0].state as string;
      // State may remain AWAITING_EMAIL_OTP (otp expired, user needs to re-submit)
      // or AWAITING_EMAIL (engine may reset on expiry) — but never PRE_AUTH_TOKEN_ISSUED
      expect(stateAfter).not.toBe("PRE_AUTH_TOKEN_ISSUED");
      expect(stateAfter).not.toBe("EMAIL_CONFIRMED");

      // otp.expired event was logged
      const expiredEvent = logEvents.find((e) => e.event === "registration.otp.expired");
      expect(expiredEvent).toBeDefined();

      // User was told the OTP expired
      const expiredMsg = sent.find((m) => m.message.toLowerCase().includes("expired"));
      expect(expiredMsg).toBeDefined();
    } finally {
      engine.stop();
      try {
        const active = await repo.findActiveByChannelUser("cli", userId);
        if (active) {
          await repo.transition(active.id, "EXPIRED");
        }
      } catch { /* ignore cleanup errors */ }
    }
  });

});

// ─── AC-008-4: Rate limit — 6th send throws RateLimitError (unit, no integration gate) ───
//
// This is the same in-memory rate limiter exercised by AC-002 but named for AC-008 to make
// AC traceability explicit. No CELLO_ENV=local or SES_INTEGRATION_TEST=true required.

describe("SesOtpDeliveryProvider — AC-008-4: rate limit (unit, always runs)", () => {
  it("6th call to sendOtp() within 1 hour throws RateLimitError (in-memory rate limiter)", async () => {
    const targetEmail = "ac008-ratelimit@example.com";
    const provider = new SesOtpDeliveryProvider({
      sesClient: buildFakeClient(makeSendMock({ MessageId: "msg-id-rate" })),
      fromAddress: "noreply@mail.mygentic.ai",
      logger: makeLogger(),
    });

    for (let i = 0; i < 5; i++) {
      await provider.sendOtp(targetEmail, "999999");
    }

    // 6th call to same address must throw RateLimitError without calling SES
    await expect(provider.sendOtp(targetEmail, "888888")).rejects.toBeInstanceOf(RateLimitError);
  });
});
