/**
 * DOD-M15-RELAYABUSE-1 — per-depositor rate limiting on content-park deposits.
 *
 * The audit's first finding is *"No rate limiting of any kind"*, and the park deposit is the
 * sharpest instance: unauthenticated by design, 4 MiB frames, a shared store.
 *
 * ⚠️ **A BOUND IS NOT A LIMIT, which is why this exists alongside the store caps.** The caps decide
 * how much can be STORED; without a limiter an attacker still spends the relay's CPU, stream slots
 * and disk writes at line rate, and still churns a victim's mailbox against the per-recipient cap
 * indefinitely. This decides how fast a deposit can be ATTEMPTED.
 *
 * ⚠️ **And it is honestly a speed bump, not a gate.** It keys on the Noise-authenticated peer id —
 * a real cryptographic identity for the connection, which was available all along and discarded,
 * and which is **cheap to rotate**. It defeats the ordinary abusive case (one peer, many deposits)
 * and raises the cost of the determined one. The hard bound is the store's.
 */

import { describe, it, expect } from "vitest";
import { DepositRateLimiter, DEFAULT_DEPOSIT_RATE_LIMIT } from "../deposit-rate-limiter.js";

const PEER_A = "12D3KooWDepositorA";
const PEER_B = "12D3KooWDepositorB";

describe("DOD-M15-RELAYABUSE-1 — the deposit rate limiter", () => {
  it("★★★ one peer past the limit is REFUSED, and told when to come back", () => {
    /**
     * The behaviour the whole unit is for. Note the assertion on `retryAfterMs`: a refusal that does
     * not say when to retry turns every client into a busy-loop, which is the flood the limiter was
     * meant to stop, generated by well-behaved software.
     */
    const rl = new DepositRateLimiter({ maxPerWindow: 3, windowMs: 60_000 });
    const t = 1_000_000;

    expect(rl.check(PEER_A, t).allowed, "first is fine").toBe(true);
    expect(rl.check(PEER_A, t + 1).allowed).toBe(true);
    expect(rl.check(PEER_A, t + 2).allowed, "at the limit, still allowed").toBe(true);

    const over = rl.check(PEER_A, t + 3);
    expect(over.allowed, "the fourth in the window must be refused").toBe(false);
    expect(over.count, "and the count must be the real number, for the log").toBe(4);
    expect(
      over.retryAfterMs,
      "a refusal that does not say when to retry turns a client into a busy-loop — the very flood " +
        "this exists to stop, produced by well-behaved software",
    ).toBeGreaterThan(0);
  });

  it("★★★ ONE PEER'S FLOOD DOES NOT REFUSE ANOTHER — the limit is per-depositor, not global", () => {
    /**
     * ⚠️ THE PROPERTY THAT MAKES THIS SAFE TO SHIP. A global limiter would let one attacker deny the
     * park path to every honest sender — turning an abuse control into the outage it was meant to
     * prevent, which is precisely the shape the store's first bound got wrong.
     */
    const rl = new DepositRateLimiter({ maxPerWindow: 2, windowMs: 60_000 });
    const t = 2_000_000;

    rl.check(PEER_A, t);
    rl.check(PEER_A, t + 1);
    expect(rl.check(PEER_A, t + 2).allowed, "peer A is over its own limit").toBe(false);

    expect(
      rl.check(PEER_B, t + 3).allowed,
      "peer B must be unaffected — one peer's abuse must never refuse everyone else",
    ).toBe(true);
  });

  it("★★ the window RESETS — a limiter that never forgives is a permanent ban", () => {
    const rl = new DepositRateLimiter({ maxPerWindow: 1, windowMs: 1_000 });
    const t = 3_000_000;

    expect(rl.check(PEER_A, t).allowed).toBe(true);
    expect(rl.check(PEER_A, t + 10).allowed, "over the limit inside the window").toBe(false);
    expect(
      rl.check(PEER_A, t + 1_001).allowed,
      "and allowed again once the window has passed — this is a rate limit, not a ban list",
    ).toBe(true);
  });

  it("★★★ THE LIMITER IS NOT ITSELF A MEMORY LEAK — idle peers are dropped", () => {
    /**
     * ⚠️ A limiter keyed on an ATTACKER-CHOSEN identifier is a memory-exhaustion surface in its own
     * right, and this exact defect was found in the park store one commit earlier: every deposit
     * created a bucket and nothing ever removed an empty one, so a refused flood cost the attacker
     * no disk and still grew the relay's heap forever.
     *
     * Shipping a limiter with that shape would have re-introduced the same defect inside the fix
     * for it.
     */
    const rl = new DepositRateLimiter({ maxPerWindow: 5, windowMs: 1_000 });
    const t = 4_000_000;

    for (let i = 0; i < 500; i++) rl.check(`peer-${String(i)}`, t);
    expect(rl.size(), "precondition: they were all tracked").toBe(500);

    rl.check("someone-later", t + 1_001);
    expect(
      rl.size(),
      "peers idle beyond a window must be forgotten — otherwise an attacker mints identities and " +
        "grows the relay's heap for free, which is the defect this milestone just fixed elsewhere",
    ).toBeLessThanOrEqual(1);
  });

  it("★★ an ABSENT peer id is allowed through, deliberately", () => {
    /**
     * The transport did not give us an authenticated identity for this stream. Refusing on that
     * basis would make a transport detail into an availability failure — a deposit path that starts
     * refusing everyone because a field went missing is a worse outage than the abuse it prevents.
     * The store's bounds still apply to those deposits.
     */
    const rl = new DepositRateLimiter({ maxPerWindow: 1, windowMs: 60_000 });
    const t = 5_000_000;
    expect(rl.check(undefined, t).allowed).toBe(true);
    expect(rl.check(undefined, t + 1).allowed, "and it is not accumulated against a shared bucket").toBe(true);
    expect(rl.check("", t + 2).allowed, "an empty string is the same case").toBe(true);
  });

  it("★ the default is sized for the path's real use, not for a benchmark", () => {
    /**
     * Parking is for a counterparty who is briefly offline: a legitimate sender parks a handful. The
     * number is deliberately boring — far above any real conversation, far below what a flood needs.
     */
    expect(DEFAULT_DEPOSIT_RATE_LIMIT.maxPerWindow).toBe(30);
    expect(DEFAULT_DEPOSIT_RATE_LIMIT.windowMs).toBe(60_000);
  });
});
